spring.datasource.url=jdbc:postgresql://localhost:5432/syntopical_notes
spring.datasource.username=admin
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate

# logging.level.liquibase=DEBUG
# logging.level.org.liquibase=DEBUG
