/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rahim.syntopicalnotes;

// import javax.sql.DataSource;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SyntopicalNotes {

    public static void main(String[] args) {
        SpringApplication.run(SyntopicalNotes.class, args);
    }
}
